FROM python:alpine3.10
WORKDIR /app 
COPY . /app
# RUN pip install -r requirements.txt
EXPOSE 4000
CMD python ./hello_docker.py

#COPY requirements.txt /app/requirements.txt
#ENTRYPOINT ["python", "./hello_docker.py"]